# Generated by Django 5.2.8 on 2025-11-27 03:00

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, validators=[biblioteca.models.validar_nombre_autor]),
        ),
    ]
