# Generated by Django 5.2.8 on 2025-11-28 02:21

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_libro_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(validators=[biblioteca.models.validar_calificacion]),
        ),
    ]
